name = "PEPSKitBenchmarks"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
PEPSKit = "52969e89-939e-4361-9b68-9bc7cde4bdeb"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"

[sources]
PEPSKit = {path = ".."}
