"""
$(TYPEDEF)

Environment of a boundary MPS contraction of a network with a single-site unit cell which is
invariant under rotations and Hermitian reflections.

Such an environment consists of a single uniform MPS approximating the leading eigenvector
of the row-to-row transfer matrix of the network, given in its left- and right-gauged form
`AL` and `AR` along with the corresponding bond tensor `C`, as well as the left and right
environments `GL` and `GR`. The latter are obtained as the left and right fixed points of
the MPS-network-MPS transfer matrix.

## Fields

$(TYPEDFIELDS)

## Constructors

    SymmetricBoundaryMPSEnv([f=randn, T=scalartype(network)], network, Venv::ElementarySpace)

Construct a symmetric boundary MPS environment for a given `network` with all virtual
environment spaces given by `Venv`, where the tensor entries are generated by `f` with
scalar type `T`. Here, `network` can be an [`InfiniteSquareNetwork`](@ref) or anything that
can be converted into one, such as an [`InfinitePEPS`](@ref) or an
[`InfinitePartitionFunction`](@ref).
"""
struct SymmetricBoundaryMPSEnv{TC, TE}
    "left-gauged MPS tensor"
    AL::TE
    "right-gauged MPS tensor"
    AR::TE
    "MPS bond tensor"
    C::TC
    "left environment"
    GL::TE
    "right environment"
    GR::TE
end

# unpack an environment into its constituent tensors
_unpack(env::SymmetricBoundaryMPSEnv) = (env.AL, env.AR, env.C, env.GL, env.GR)

#
## initialization
#

"""
    _initialize_GL([f=randn, T=scalartype(A)], A::GenericMPSTensor, O)
    _initialize_GR([f=randn, T=scalartype(A)], A::GenericMPSTensor, O)

Initialize a left or right environment for an MPS tensor `A` and a local network tensor
`O`, with entries generated by `f` and scalar type `T`.
"""
function _initialize_GL(f, ::Type{T}, A::GenericMPSTensor, O) where {T}
    V = left_virtualspace(A) ⊗ _elementwise_dual(west_virtualspace(O)) ← left_virtualspace(A)
    return f(T, V)
end
function _initialize_GR(f, ::Type{T}, A::GenericMPSTensor, O) where {T}
    V = right_virtualspace(A) ⊗ _elementwise_dual(east_virtualspace(O)) ← right_virtualspace(A)
    return f(T, V)
end

function SymmetricBoundaryMPSEnv(network::InfiniteSquareNetwork, Venv::ElementarySpace)
    return SymmetricBoundaryMPSEnv(randn, scalartype(network), network, Venv)
end
function SymmetricBoundaryMPSEnv(
        state::Union{InfinitePEPS, InfinitePartitionFunction}, args...
    )
    return SymmetricBoundaryMPSEnv(InfiniteSquareNetwork(state), args...)
end
function SymmetricBoundaryMPSEnv(
        f, T, state::Union{InfinitePEPS, InfinitePartitionFunction}, args...
    )
    return SymmetricBoundaryMPSEnv(f, T, InfiniteSquareNetwork(state), args...)
end
function SymmetricBoundaryMPSEnv(
        f, ::Type{T}, network::InfiniteSquareNetwork, Venv::ElementarySpace
    ) where {T}
    size(network) == (1, 1) ||
        throw(ArgumentError("symmetric boundary MPS environments require a single-site unit cell"))
    O = network[1, 1]

    # initialize the MPS tensors by constructing an actual MPS, this improves stability
    A = f(T, Venv ⊗ _elementwise_dual(north_virtualspace(O)) ← Venv)
    mps = InfiniteMPS([A])
    AL, AR, C = only(mps.AL), only(mps.AR), only(mps.C)

    GL = _initialize_GL(f, T, AL, O)
    GR = _initialize_GR(f, T, AR, O)

    return SymmetricBoundaryMPSEnv(AL, AR, C, GL, GR)
end

#
## interface
#

function Base.:(==)(env₁::SymmetricBoundaryMPSEnv, env₂::SymmetricBoundaryMPSEnv)
    return all(splat(==), zip(_unpack(env₁), _unpack(env₂)))
end
function Base.isapprox(
        env₁::SymmetricBoundaryMPSEnv, env₂::SymmetricBoundaryMPSEnv; kwargs...
    )
    return all(zip(_unpack(env₁), _unpack(env₂))) do (t₁, t₂)
        return isapprox(t₁, t₂; kwargs...)
    end
end

Base.real(env::SymmetricBoundaryMPSEnv) = SymmetricBoundaryMPSEnv(map(real, _unpack(env))...)
Base.complex(env::SymmetricBoundaryMPSEnv) = SymmetricBoundaryMPSEnv(map(complex, _unpack(env))...)
Base.similar(env::SymmetricBoundaryMPSEnv) = SymmetricBoundaryMPSEnv(map(similar, _unpack(env))...)
Base.copy(env::SymmetricBoundaryMPSEnv) = SymmetricBoundaryMPSEnv(map(copy, _unpack(env))...)

function Base.:+(env₁::SymmetricBoundaryMPSEnv, env₂::SymmetricBoundaryMPSEnv)
    return SymmetricBoundaryMPSEnv(map(+, _unpack(env₁), _unpack(env₂))...)
end
function Base.:-(env₁::SymmetricBoundaryMPSEnv, env₂::SymmetricBoundaryMPSEnv)
    return SymmetricBoundaryMPSEnv(map(-, _unpack(env₁), _unpack(env₂))...)
end
function Base.:*(α::Number, env::SymmetricBoundaryMPSEnv)
    return SymmetricBoundaryMPSEnv(map(Base.Fix1(*, α), _unpack(env))...)
end

"""
    update!(env::SymmetricBoundaryMPSEnv, env´::SymmetricBoundaryMPSEnv)

Update the environment `env` in-place with the contents of `env´`.
"""
function update!(
        env::SymmetricBoundaryMPSEnv{TC, TE}, env´::SymmetricBoundaryMPSEnv{TC, TE}
    ) where {TC, TE}
    foreach(splat(copy!), zip(_unpack(env), _unpack(env´)))
    return env
end

#
## VectorInterface
#

function VI.scalartype(::Type{SymmetricBoundaryMPSEnv{TC, TE}}) where {TC, TE}
    return promote_type(scalartype(TC), scalartype(TE))
end

function VI.zerovector(env::SymmetricBoundaryMPSEnv, ::Type{S}) where {S <: Number}
    return SymmetricBoundaryMPSEnv(map(t -> zerovector(t, S), _unpack(env))...)
end
function VI.zerovector!(env::SymmetricBoundaryMPSEnv)
    foreach(zerovector!, _unpack(env))
    return env
end
VI.zerovector!!(env::SymmetricBoundaryMPSEnv) = zerovector!(env)

function VI.scale(env::SymmetricBoundaryMPSEnv, α::Number)
    return SymmetricBoundaryMPSEnv(map(t -> scale(t, α), _unpack(env))...)
end
function VI.scale!(env::SymmetricBoundaryMPSEnv, α::Number)
    foreach(t -> scale!(t, α), _unpack(env))
    return env
end
function VI.scale!(
        env₁::SymmetricBoundaryMPSEnv, env₂::SymmetricBoundaryMPSEnv, α::Number
    )
    foreach(zip(_unpack(env₁), _unpack(env₂))) do (t₁, t₂)
        return scale!(t₁, t₂, α)
    end
    return env₁
end
VI.scale!!(env::SymmetricBoundaryMPSEnv, α::Number) = scale!(env, α)
function VI.scale!!(
        env₁::SymmetricBoundaryMPSEnv, env₂::SymmetricBoundaryMPSEnv, α::Number
    )
    return scale!(env₁, env₂, α)
end

function VI.add(
        env₁::SymmetricBoundaryMPSEnv, env₂::SymmetricBoundaryMPSEnv, α::Number, β::Number
    )
    return SymmetricBoundaryMPSEnv(
        map((t₁, t₂) -> add(t₁, t₂, α, β), _unpack(env₁), _unpack(env₂))...
    )
end
function VI.add!(
        env₁::SymmetricBoundaryMPSEnv, env₂::SymmetricBoundaryMPSEnv, α::Number, β::Number
    )
    foreach(zip(_unpack(env₁), _unpack(env₂))) do (t₁, t₂)
        return add!(t₁, t₂, α, β)
    end
    return env₁
end
function VI.add!!(
        env₁::SymmetricBoundaryMPSEnv, env₂::SymmetricBoundaryMPSEnv, α::Number, β::Number
    )
    return add!(env₁, env₂, α, β)
end

function VI.inner(env₁::SymmetricBoundaryMPSEnv, env₂::SymmetricBoundaryMPSEnv)
    return sum(splat(inner), zip(_unpack(env₁), _unpack(env₂)))
end
VI.norm(env::SymmetricBoundaryMPSEnv) = norm(_unpack(env))
