env:
  SECRET_CODECOV_TOKEN: "MH6hHjQi7vG2V1Yfotv5/z5Dkx1k5SdyGYlGTFXiQr22XksJgsXaBuvFKUrjC7JwcpBsOVU8103LuMKl3m7VJ35WzHZrOssYycVbdGcb2kloc6xvUOsN2R5BrhCQ4Pii0l6ZeVRjCnZVkcmb0Rf4glGFyfibCrqniry8RLhblsuFKFsijRK4OxiWYEs1IvUulN+ER8tEsEtw4+ZqC5nbLGMSnUG/saPkDQOVIBscvikbKEnBcCXBheGPktF+Y/cy/1Xa+FiBPoZcypwTeAjKG1g0MqyHXjaYekb/7fekaj+hukGaeJSCXxY8KEb2IZCh+Y36Tp6y6qsIp/AdtEnCpQ==;U2FsdGVkX18WQxvGLspPwzC4aDe+U7TXU+itebTbgh8LUkE6GukxxReHYiDZ6IrBiVvSGTVJMquW0c8KsOI1pw=="

steps:
  - label: "Julia {{matrix.julia}} -- {{matrix.queue}}"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.julia}}"
      - JuliaCI/julia-test#v1:
          test_args: "{{matrix.group}}"
      - JuliaCI/julia-coverage#v1:
          dirs:
            - src
            - ext
    agents:
      queue: "{{matrix.queue}}"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 90
    matrix:
      setup:
        julia:
          - "1.10"
          - "1.12"
        queue:
          - "cuda"
          - "rocm"
        group:
          - "boundarymps"
          - "bp"
          - "ctmrg"
          - "timeevol"
          - "toolbox"

