name: Docs preview comment
on:
  pull_request:
    types: [labeled]

permissions:
  pull-requests: write
jobs:
  pr_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR comment
        if: github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name && github.event.label.name == 'documentation'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: 'After the build completes, the updated documentation will be available [here](https://quantumkithub.github.io/PEPSKit.jl/previews/PR${{ github.event.number }}/)'
          comment-tag: 'preview-doc'
